export const ErrorCodes = {
  // Validation
  SCORING_WEIGHT_INVALID: 'SCORING_WEIGHT_INVALID',
  SCORING_RULE_NOT_FOUND: 'SCORING_RULE_NOT_FOUND',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  TASK_NOT_SCHEDULED: 'TASK_NOT_SCHEDULED',
  TASK_IS_PINNED: 'TASK_IS_PINNED',
  INVALID_STRATEGY: 'INVALID_STRATEGY',
  INVALID_PRIORITY: 'INVALID_PRIORITY',

  // Engine
  SOLVE_FAILED: 'SOLVE_FAILED',
  ENGINE_EXCEPTION: 'ENGINE_EXCEPTION',
  CHAIN_EVALUATION_FAILED: 'CHAIN_EVALUATION_FAILED',
  NO_FEASIBLE_SCHEDULE: 'NO_FEASIBLE_SCHEDULE',

  // Config
  STATE_NOT_LOADED: 'STATE_NOT_LOADED',
  SCORING_CONFIG_MISSING: 'SCORING_CONFIG_MISSING',
  TENANT_CONFIG_MISSING: 'TENANT_CONFIG_MISSING',
  HORIZON_NOT_SET: 'HORIZON_NOT_SET',

  // System
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  TIMEOUT: 'TIMEOUT',
} as const;

export type ErrorCategory = 'validation' | 'engine' | 'config' | 'system';
